In [36]:
import csv
import numpy as np

csvFile = open("data.csv")
reader = csv.reader(csvFile)

result = []

for item in reader:
    # print(type(item))
    try:
        result.append([float(item[0]), float(item[1]),float(item[2]),float(item[3]),float(item[4])])
    except:
        print(" is type error")
    if(reader.line_num == 21):
        break

csvFile.close()
# print(result)
arr = np.asarray(result)
arr


 is type error


array([[330.994152 ,  91.503268 , 252.6315789,  14.0350877,  32.4090608],
       [319.1709845, 177.489177 , 243.4782609,  11.0671937,  68.3254517],
       [230.4347826,  87.719298 , 150.       ,   7.8947368,  44.7213595],
       [244.6428571, 196.969697 , 200.       ,  16.6666667,  55.4700196],
       [300.9433962, 317.028986 , 200.       ,   8.3333333,  78.7400787],
       [370.0404858, 182.788051 , 241.025641 ,   6.34278  ,  49.4652253],
       [339.7027601, 161.904762 , 248.6486486,   6.9069069,  55.0176119],
       [160.       , 416.666667 , 200.       ,  50.       ,  31.6227766],
       [247.6190476, 115.384615 , 171.4285714,  13.1868132,  40.824829 ],
       [759.0954774,  58.039216 , 215.3846154,   4.2232278,  44.0315286],
       [501.8145161,  86.021505 , 250.       ,   8.0645161,  45.8257569],
       [190.5660377, 192.982456 , 170.       ,   8.9473684,  69.8490711],
       [398.2993197,  81.792319 , 205.1282051,   5.3981107,  50.5284573],
       [247.4576271,  59.52381  , 144.

In [26]:
k_cen=np.array([arr[1],arr[2],arr[3]])
k_cen

array([[319.1709845, 177.489177 , 243.4782609,  11.0671937,  68.3254517],
       [230.4347826,  87.719298 , 150.       ,   7.8947368,  44.7213595],
       [244.6428571, 196.969697 , 200.       ,  16.6666667,  55.4700196]])

In [27]:
node_cen = np.empty([5], dtype=float)
for item in arr:
    for i in range(5):
        node_cen[i] += item[i]

node_cen = node_cen/len(arr)
node_cen


array([332.26110471, 151.80663587, 200.72461569,  12.1254901 ,
        49.8340916 ])

In [30]:
#计算距离
dist=[]
for cen in k_cen:
    d = cen-node_cen
    d = d*d
    d = np.sum(d)/len(node_cen)
    dist.append(d)
clo_k = k_cen[0]
dist

[600.3737467973967, 3418.5625381535383, 1953.9140885109325]

In [35]:
col_max = np.max(arr, axis=0)
print("col max is ", col_max)
col_min = np.min(arr, axis=0)
print("col min is ", col_min)
# v = np.array([5], dtype=float)
# for cen in k_cen:
#     u = cen - clo_k
#     for i in range(len(u)):
#         if u[i]>0:
#             v[i]=col_max[i]
#         else:
#             v[i]=col_min[i]
#     dist_clo_v=np.sum((clo_k-v)**2)/len(v)
#     dist_k_v=np.sum((cen-v)**2)/len(v)




col max is  [759.0954774 416.666667  252.6315789  50.         78.7400787]
col min is  [114.2857143  50.        109.0909091   4.2232278  26.3523138]
