In [21]:
import pandas as pd 
import numpy as np

df=pd.read_csv("data.csv", header=None, sep=',', usecols=[x for x in range(5)], nrows=20)
df = df.values.tolist()
df = np.array(df)
# print(len(df))
print(df)
np.sum(df, axis=0)
# print(df[10,0]+df[11.0]+df[15,0])

[[  0.         85.        226.0869565  10.2766798  35.0401292]
 [330.994152   91.503268  252.6315789  14.0350877  32.4090608]
 [319.1709845 177.489177  243.4782609  11.0671937  68.3254517]
 [230.4347826  87.719298  150.          7.8947368  44.7213595]
 [244.6428571 196.969697  200.         16.6666667  55.4700196]
 [300.9433962 317.028986  200.          8.3333333  78.7400787]
 [370.0404858 182.788051  241.025641    6.34278    49.4652253]
 [339.7027601 161.904762  248.6486486   6.9069069  55.0176119]
 [160.        416.666667  200.         50.         31.6227766]
 [247.6190476 115.384615  171.4285714  13.1868132  40.824829 ]
 [759.0954774  58.039216  215.3846154   4.2232278  44.0315286]
 [501.8145161  86.021505  250.          8.0645161  45.8257569]
 [190.5660377 192.982456  170.          8.9473684  69.8490711]
 [398.2993197  81.792319  205.1282051   5.3981107  50.5284573]
 [247.4576271  59.52381   144.8275862   5.1724138  46.5352864]
 [120.        200.        114.2857143  19.047619   30.6

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices